"""to the web

Revision ID: 744d71a22a58
Revises: 
Create Date: 2021-06-13 18:20:14.349417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744d71a22a58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.String(length=50), nullable=False),
    sa.Column('track_source', sa.String(length=30), nullable=True),
    sa.Column('track_title', sa.String(length=100), nullable=True),
    sa.Column('artist_name', sa.String(length=50), nullable=True),
    sa.Column('track_duration', sa.Float(), nullable=True),
    sa.Column('happy_rating', sa.Float(), nullable=True),
    sa.Column('sadness_rating', sa.Float(), nullable=True),
    sa.Column('annoying_rating', sa.Float(), nullable=True),
    sa.Column('anxious_rating', sa.Float(), nullable=True),
    sa.Column('energizing_rating', sa.Float(), nullable=True),
    sa.Column('neutral_rating', sa.Float(), nullable=True),
    sa.Column('dreamy_rating', sa.Float(), nullable=True),
    sa.Column('relaxing_rating', sa.Float(), nullable=True),
    sa.Column('rating_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_rating_annoying_rating'), 'sentiment_rating', ['annoying_rating'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_anxious_rating'), 'sentiment_rating', ['anxious_rating'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_artist_name'), 'sentiment_rating', ['artist_name'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_dreamy_rating'), 'sentiment_rating', ['dreamy_rating'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_energizing_rating'), 'sentiment_rating', ['energizing_rating'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_happy_rating'), 'sentiment_rating', ['happy_rating'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_neutral_rating'), 'sentiment_rating', ['neutral_rating'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_rating_date'), 'sentiment_rating', ['rating_date'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_relaxing_rating'), 'sentiment_rating', ['relaxing_rating'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_sadness_rating'), 'sentiment_rating', ['sadness_rating'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_track_duration'), 'sentiment_rating', ['track_duration'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_track_id'), 'sentiment_rating', ['track_id'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_track_source'), 'sentiment_rating', ['track_source'], unique=False)
    op.create_index(op.f('ix_sentiment_rating_track_title'), 'sentiment_rating', ['track_title'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_sentiment_rating_track_title'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_track_source'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_track_id'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_track_duration'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_sadness_rating'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_relaxing_rating'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_rating_date'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_neutral_rating'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_happy_rating'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_energizing_rating'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_dreamy_rating'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_artist_name'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_anxious_rating'), table_name='sentiment_rating')
    op.drop_index(op.f('ix_sentiment_rating_annoying_rating'), table_name='sentiment_rating')
    op.drop_table('sentiment_rating')
    # ### end Alembic commands ###
